name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    paths:
      - 'tabbyapi-latest-commit-sha.txt'

env:
  IMAGE_NAME: andecy64/tabbyapi-hf

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BASE_IMAGE:
          - 12.3.2-runtime-ubuntu22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: .
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          provenance: mode=max
          sbom: true
          tags: ${{ env.IMAGE_NAME }}:${{ matrix.BASE_IMAGE }}-runpod
          push: true
          build-args: BASE_IMAGE=${{ matrix.BASE_IMAGE }}
